Improved Filtering options
iotaledger/inx-indexer pull request #131
Opened 2023-09-11 16:23 UTC by alexsporn

- Added `unlockableByAddress` filter to `/outputs/basic`, `/outputs/alias` and `outputs/nft` routes which checks for the different address unlocks with an `OR` condition
- Added new `/outputs` route that combines Basic, Alias and NFT outputs in the result. It supports some of the common filtering options including the above `unlockableByAddress` one.

2023-09-15 10:22 UTC, muXxer requested changes

2023-09-15 10:22 UTC, muXxer commented on pkg/server/routes.go
> +		value, err := httpserver.ParseUint32QueryParam(c, QueryParameterMinNativeTokenCount, iotago.MaxNativeTokenCountPerOutput)
Is that `iotago.MaxNativeTokenCountPerOutput` correct here?

2023-09-15 10:29 UTC, muXxer commented on pkg/server/routes.go
> +		value, err := httpserver.ParseUint32QueryParam(c, QueryParameterMinNativeTokenCount, iotago.MaxNativeTokenCountPerOutput)
It's correct, because its the max value, but better add a comment here.

2023-09-15 10:48 UTC, muXxer approved these changes

2023-09-18 07:11 UTC, alexsporn commented
```
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/basic?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/basic?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (1.14ms)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/basic?expirationReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/basic?expirationReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (444.95µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/basic?storageDepositReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/basic?storageDepositReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (384µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/nft?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/nft?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (4.74ms)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/nft?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy&cursor=64bba6c3c268262aa92fea1cc830361b67d42939d39038621a18d66168812e462edc5f8c2800.1000
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/nft?address=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy&cursor=64bba6c3c268262aa92fea1cc830361b67d42939d39038621a18d66168812e462edc5f8c2800.1000 (1.78ms)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/nft?expirationReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/nft?expirationReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (437.91µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/nft?storageDepositReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/nft?storageDepositReturnAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (353.04µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/alias?governor=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/alias?governor=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (985.37µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs/alias?stateController=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs/alias?stateController=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (704.41µs)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs?unlockableByAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs?unlockableByAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (5.1ms)
2023/09/18 09:09:08 --> GET http://localhost:14265/api/indexer/v1/outputs?cursor=64bba5eaea219a40b17b1f8cae71b65ec9079081744a1bcda9961916a432cb5a7c4999872300.1000&unlockableByAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy
2023/09/18 09:09:08 <-- 200 http://localhost:14265/api/indexer/v1/outputs?cursor=64bba5eaea219a40b17b1f8cae71b65ec9079081744a1bcda9961916a432cb5a7c4999872300.1000&unlockableByAddress=rms1qpllaj0pyveqfkwxmnngz2c488hfdtmfrj3wfkgxtk4gtyrax0jaxzt70zy (2.56ms)
Sum: 1317
Combined: 1317
Equal: true
```

The sum of all requests equals the combined results, so it is looking good

2023-09-18 07:17 UTC, merged